# Generated by Django 3.1.3 on 2020-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.IntegerField(verbose_name=int)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField(max_length=10)),
                ('categoria', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(verbose_name=bool)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venda', models.IntegerField(verbose_name=int)),
                ('valorTotal', models.FloatField(max_length=100)),
                ('valorPago', models.FloatField(max_length=100)),
                ('data_venda', models.DateField()),
            ],
        ),
    ]
