# Generated by Django 3.1.3 on 2020-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_itensvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvenda',
            name='valorUnitario',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
