# Generated by Django 3.1.3 on 2020-12-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_itensvenda_valorunitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensvenda',
            name='valorUnitario',
        ),
    ]
