# Generated by Django 3.1.3 on 2020-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_itensvenda_valorunitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvenda',
            name='valorUnitario',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
